### ISSUE TITLE
Gradients break on Transform2D different than identity.

### ISSUE THREAD

**Issue by AnuraDev** [floppyhammer/pathfinder-cpp#3]
As the title states if you append svg scene with a different transform (for example you scale it uniformly x1.5) gradients stop to lit the paths. the same applies to dx9/dx11 pipelines. not sure if it applies to the original pathfinder, need to check but the code is more convoluted than your port, well done! <3 ok it seems what gradient bounds/boxes are generated for the original scene, and in case of transformed it goes out of bounds. so the transformation is applied in the wrong place or isn't applied at all.

/**
 * @brief Convert NanoSVG paint to our own type.
 * @param nsvg_paint NanoSVG paint
 * @return Paint
 */
Paint convert_nsvg_paint(NSVGpaint nsvg_paint) {
    Paint paint;

    // FIXME: Non-Identity transform will cause incorrect gradient (both linear and radical) rendering.

ok i see

**Comment by floppyhammer** [comment]
The FIXME note you mentioned is more related to SVG parsing and might have nothing to do with this issue. An identity transform provided to `append_scene` still results in a wrong gradient effect.
