### ISSUE TITLE
Patterns as stroke paint don't repeat.

### ISSUE THREAD

**Issue by AnuraDev** [floppyhammer/pathfinder-cpp#5]
If you add this to the App constructor you can observe what it just stretches the last pixels. in both dx9/dx11.
also some kind of clipping bug appears https://i.imgur.com/2dbKAf1.png (and garbage pixels)
also i think pattern should start from objects bounding box origin not canvas, but idk how hard it would be to fix (without just adding translate to transformation).

    auto image_buffer = ImageBuffer::from_memory(load_file_as_bytes("../assets/sea.png"), false);
    auto image2 = std::make_shared<Image>(image_buffer->get_size(), image_buffer->to_rgba_pixels());

    Path2d path;
    path.move_to(260.0, 260.0);
    path.line_to(460.0, 260.0);
    path.line_to(460.0, 460.0);
    path.line_to(260.0, 460.0);
    path.close_path();

    canvas->set_line_width(50.0);
    auto pattern = Pattern::from_image(image2);
    pattern.apply_transform(Transform2::from_scale(Vec2F(1, 1)));
    pattern.set_repeat_x(true);
    pattern.set_repeat_y(true);
    canvas->set_stroke_paint(Paint::from_pattern(pattern));

    canvas->stroke_path(path);

**Comment by floppyhammer** [comment]
@AnuraDev It should be easy to change the pattern origin but I'm not sure the object's bounding box should be the origin. For gradient, the transformation starts from the canvas origin. It's reasonable for image patterns to take the same way.

As for the clipping bug, could you elaborate on how to reproduce it?

**Comment by AnuraDev** [comment]
> @AnuraDev It should be easy to change the pattern origin but I'm not sure the object's bounding box should be the origin. For gradient, the transformation starts from the canvas origin. It's reasonable for image patterns to take the same way.
> 
> As for the clipping bug, could you elaborate on how to reproduce it?

Yes, i checked the standard (web canvas) filling is from canvas origin so it's fine (my suggestion was wrong).

About clipping, probably the problem lies in something else but first time i tested it looked like quad was broken down into 2 tris, so i called it clipping but here what i was talking about this diagonal tiling looks weird and is almost the same for dx9 and dx11. in case of dx9 you get transparency in place of garbage color pixels.

![pf_render_artifacts](https://github.com/floppyhammer/pathfinder-cpp/assets/11312170/40779911-8279-4931-88d6-f155dfc399f4)

to reproduce attach the code from original post at the end of the scene with most stuff enabled like on the screen. the minimal set should be image + pattern.

![pf_render_artifacts2](https://github.com/floppyhammer/pathfinder-cpp/assets/11312170/58fb283f-5f5e-464d-aaef-90ebc09fc570)

**Comment by floppyhammer** [comment]
I believe the original Rust repo has got the same issue as well.
