### ISSUE TITLE
dx11 pipeline rendering Y-inverted

### ISSUE THREAD

**Issue by AnuraDev** [floppyhammer/pathfinder-cpp#6]
For some reason it's inverted idk why maybe it has a reason on some platform but on windows it's just flipped. to fix you need to remove the subtraction in src/shaders/d3d11/tile.comp

from

ivec2 toImageCoords(ivec2 coords) {
    return ivec2(coords.x, int(uFramebufferSize.y) - coords.y);
}

to

ivec2 toImageCoords(ivec2 coords) {
    return ivec2(coords.x, coords.y);
}

and regenerate shaders.

**Comment by floppyhammer** [comment]
Unfortunately, your suggestion will turn a render target pattern upside down.

dx9
<img width="198" alt="image" src="https://github.com/floppyhammer/pathfinder-cpp/assets/28705694/c6d3c864-790f-48c4-9298-bfea7d6210a5">

dx11
<img width="199" alt="image" src="https://github.com/floppyhammer/pathfinder-cpp/assets/28705694/55c7687d-419f-4d41-9d6e-bb2d03eb67f5">

**Comment by AnuraDev** [comment]
first what comes to mind is to keep the shader fix and transform the render target like this

https://i.imgur.com/MPnU1EF.png

but it's probably wrong i think you need to do a "inverted" matrix mult, the idea is to compensate flipped y (-1 scale) offset. even it's "hacky" i don't see any real problem to fix it with adjusted transform.

**Comment by floppyhammer** [comment]
@AnuraDev It's actually quite simple to solve. I had made some extra fixup to handle some image flipping issue in dx11 which now no longer exists. Keeping the shader fix and removing those obsolete code, now no more annoying flipped dst texture in dx11.

**Comment by AnuraDev** [comment]
@floppyhammer great! well done UuU
