### ISSUE TITLE
Even-Odd winding not working properly on dx11

### ISSUE THREAD

**Issue by AnuraDev** [floppyhammer/pathfinder-cpp#7]
the green fill. idk how hard is it to fix, seems to be compute shader bug. (or maybe wrong parameter transfer)

dx11: https://i.imgur.com/JwbARtG.png

dx9:  https://i.imgur.com/FqYHY2V.png

**Comment by floppyhammer** [comment]
This is weird since a fix (ee0e01283099c5e8e38c75501d8ba0d31dc3c9e6 and 8cc856bc7847cf3146995325ba913908a4358788) was made quite a long time ago. In addition, a PR https://github.com/servo/pathfinder/pull/513 has been submitted to the original repo. A regression might have happend at some point.
